tag: user.common_bash_commands
-
vim editor: "vim "
jee editor: "gedit "
file copy: "cp "
file copy recursive: "cp -r "
file find: "find "
file delete: "rm "
file delete recursive: "rm -r "
file move: "mv "
lisa all human: "ls -lah\n"
make dir: "mkdir "
secure shell: "ssh "
secure shell recursive: "ssh -r "
grep inside <user.text>: "grep -rwn . -e '{text}'"
exit terminal: "exit"
