git commit amend message: "git commit -am '"
git commit amend message <user.text>: "git commit -am '{text}'"
git config user name <user.text>: "git config user.name '{text}'"
git config user email <user.text>: "git config user.email '{text}'"
git undo last commit: "git reset HEAD~ "
